### ISSUE TITLE
problem regarding KSPIE (interstellar extended)  compatibility  after 2.4.6.3 update

### ISSUE THREAD

**Issue by tonimark** [net-lisias-ksp/KSPe#26]
after update from 2.4.6.2=>2.4.6.3, this message showed up regarding broken KSPI compatibility 
![problem](https://user-images.githubusercontent.com/17166550/142723300-b02210f1-9e1e-4486-bbab-7bae744c8538.png)
I tried replacing the tweak scale folder both with the newest versions of KSPIE and tweak scale with no change

**Comment by Lisias** [comment]
I think this is a duplicate for #27 (or vice versa).

I will keep this opened for while until confirmation.

**Comment by Lisias** [comment]
@tonimark @MgnfcntBstrd 

Issue #27 apparently fixed the problem you guys described above. The fix was published on the latest Release here:

https://github.com/net-lisias-ksp/KSPApiExtensions/releases

I would appreciate if you guys could confirm the problem is solved.

Thanks in advance!

**Comment by Lisias** [comment]
Closing this issue, as I'm assuming the issue was fixed by lack of feedback.
