### ISSUE TITLE
KSP **should not** be run as Privileged User (Administrator on Windows, root on UNIX)

### ISSUE THREAD

**Issue by Lisias** [net-lisias-ksp/KSPe#56]
![410854438_10160371847562585_5386237454952154201_n](https://github.com/net-lisias-ksp/KSPe/assets/64334/1140f25c-6b6d-4781-bff3-10b91670bcd4)

If you got this message, please ask for help to fix the underlaying issue.

**NO ONE SHOULD RUN GAMES ON HIGHLY PRIVILEGED RIGHTS**.

It's a security nightmare, you are putting yourself at serious risk.

Please just don't.

**Comment by Lisias** [comment]
Related to https://github.com/TweakScale/TweakScale/discussions/304

**Comment by Lisias** [comment]
Forgot to close this.

**Comment by Ha00K-MAN** [comment]
![image](https://github.com/net-lisias-ksp/KSPe/assets/125629836/b108580e-2539-4d77-a736-f9f008dcdf16)
how can I solve this problem?

**Comment by Ha00K-MAN** [comment]
I don't know what to do

**Comment by Lisias** [comment]
@Ha00K-MAN 

> I don't know what to do

Update KSPe to the [latest version](https://github.com/net-lisias-ksp/KSPe/releases/tag/RELEASE%2F2.5.3.5) if you are running on Windows.

If you are on MacOS or Linux, then you are indeed running KSP on a privileged account, and we need to see who and why is calling KSP this way.

First step is to send me your `KSP.log` so I can check some basic information. 

Additionally, how do you launch KSP? Using a Launcher? Command Line? If you are using Linux, what's your Desktop? KDE? Gnome? XFCE?b

**Comment by Incrementalist** [comment]
I'm not entirely sure why I'm getting this error. Attached is a copy of my log file.
[KSP.log](https://github.com/net-lisias-ksp/KSPe/files/13638266/KSP.log)

**Comment by Lisias** [comment]
> I'm not entirely sure why I'm getting this error. Attached is a copy of my log file.
> [KSP.log](https://github.com/net-lisias-ksp/KSPe/files/13638266/KSP.log)

You have Scrapyard, installed by CKAN. CKAN's Scrapyards has a bug in which it installs a DLL that needs Contract Configurator.

```
[ERR 09:08:28.603] AssemblyLoader: Exception loading 'ScrapYard_ContractConfigurator': System.Reflection.ReflectionTypeLoadException: Exception of type
  at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <9577ac7a62ef43179789031239ba8798>:0
  at AssemblyLoader.LoadAssemblies () [0x000e6] in <4b449f2841f84227adfaad3149c8fdba>:0
```

So you need to install Contract Configurator, or to manually delete the file `C:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program\GameData\ScrapYard\Plugins\ScrapYard_ContractConfigurator.dll` from your rig.

On a side note, I don't mind users creating a new issue for support, besides ideally one should use discussions: https://github.com/net-lisias-ksp/KSPe/discussions/categories/support

In a way or another, I kindly ask to avoid asking for support on unrelated issues, this screws up my (already somewhat screwed) Development Process. :)

Cheers!

**Comment by Incrementalist** [comment]
> @Incrementalist :
> 
> > I'm not entirely sure why I'm getting this error. Attached is a copy of my log file.
> > [KSP.log](https://github.com/net-lisias-ksp/KSPe/files/13638266/KSP.log)
> 
> You have Scrapyard, installed by CKAN. CKAN's Scrapyards has a bug in which it installs a DLL that needs Contract Configurator.
> 
> ```
> [ERR 09:08:28.603] AssemblyLoader: Exception loading 'ScrapYard_ContractConfigurator': System.Reflection.ReflectionTypeLoadException: Exception of type
>   at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
>   at System.Reflection.Assembly.GetTypes () [0x00000] in <9577ac7a62ef43179789031239ba8798>:0
>   at AssemblyLoader.LoadAssemblies () [0x000e6] in <4b449f2841f84227adfaad3149c8fdba>:0
> ```
> 
> So you need to install Contract Configurator, or to manually delete the file `C:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program\GameData\ScrapYard\Plugins\ScrapYard_ContractConfigurator.dll` from your rig.
> 
> On a side note, I don't mind users creating a new issue for support, besides ideally one should use discussions: https://github.com/net-lisias-ksp/KSPe/discussions/categories/support
> 
> In a way or another, I kindly ask to avoid asking for support on unrelated issues, this screws up my (already somewhat screwed) Development Process. :)
> 
> Cheers!

I was asking here because it was the Privileged User error that was killing my KSP instance, with the link directly to this github issue. Thanks for the information about my Scrapyard installation, but my problem is indeed related to this issue.

**Comment by Lisias** [comment]
I'm reopening it as new information came to my attention.

On issue #64 [h3x0rof](https://github.com/h3x0rof) [commented](https://github.com/net-lisias-ksp/KSPe/issues/64#issuecomment-1850065505)

> Hello again, I probably found what caused that message to appear, I guess it was because I turned off UAC, this could cause to run every programm as Administrator, I really firstly didn't think about that days ago

**Comment by benji38** [comment]
Really? You're going to cause a damn game to CTD because I'm running it under an admin account? I'm not an idiot when it comes to security. I'm going through college for a Cyber Security degree, for fucks sake. I don't mean to come off as aggressive, but after a few hours of figuring out which mods were causing what problems, and being entirely new to modding KSP to begin with, I finally think everything's good and I'm met with what's effectively a condescending "error" screen for what's not an error. Yeah, for most users, your advice is good. But you should have a way to bypass your check.

Again, I don't meant to come across as too aggressive, but I'm at the end of my ropes here and just annoyed as hell.

**Comment by Lisias** [comment]
> Really? You're going to cause a damn game to CTD because I'm running it under an admin account?

No. You are exposing yourself to be infected by a rootkit or similar.


> Yeah, for most users, your advice is good. But you should have a way to bypass your check for people who know what they're doing.

You know, this is not a bad idea at all. I'll do it.

Until there, rollback KSPe to the last version where this message is not issued.


>  I'm not an idiot when it comes to security. I'm going through college for a Cyber Security degree, for fucks sake, I do regular backups and take my own security measures into account.

And no one told you how dangerous is to run **as super user** a program full of code from people you don't know and that potentially downloads and monkey patch things in your computer? Are you monitoring changes on the System Registry? Are you completely sure there's no binaries being dowloaded and installed on your machine?

https://github.com/net-lisias-ksp/KSPe/releases/tag/RELEASE%2F2.5.3.3


> Again, I don't meant to come across as too aggressive, but I'm at the end of my ropes here and just annoyed as hell.

But yet, aggressive you are being. And pretty annoyed I'm too, congrats - now there are two of us, annoyed as hell, one week before Christmas.

Do you enjoy doing pro-bono work when annoyed when you could be enjoying your Seasons with people that respects your time and work?

**Comment by Lisias** [comment]
Implemented on commit https://github.com/net-lisias-ksp/KSPe/commit/90db64bc82a9bd76c62f9c97256ad1556b957c54 .

No instructions will be provided. If the user is smart enough to run KSP on Privileged User without putting their ass in the line, then they are smart enough to find how to do it by himself.

If the user can't find their way on this, they should not be running games in Privileged Mode. **POINT**.

**Comment by Lisias** [comment]
I can't prevent people from killing themselves if this is what they want.

But I don't need to be part of it. I'm closing this now, no further commenting about will be accepted. Whatever I did on that commit, it's final (unless I decided to remove it later).
