### ISSUE TITLE
PLEASE HELP

### ISSUE THREAD

**Issue by EExperiment** [net-lisias-ksp/KSPe#67]
![Ekran görüntüsü 2024-02-28 111525](https://github.com/net-lisias-ksp/KSPe/assets/108108239/78b24f25-891c-4257-9288-105dd098fb03)

I delete game and mod launcher (ı download again) ı dont know how to fix that

**Comment by Lisias** [comment]
Hi, @EExperiment .

I need your KSP.log and a description of your runtime environment.

Are you using the Windows binaries on Steam Deck under Proton? Proton imposes an artificial limit of 240 (or near that) characters on the pathname, and this screws up Steam games sometimes as it uses a very long pathname on the launcher.

If you are using Windows KSP on Steam under Proton, move it to an SD card - this is a known work around for the Proton problem.

**Comment by EExperiment** [comment]
I think you want this [KSP.log](https://github.com/net-lisias-ksp/KSPe/files/14463755/KSP.log)
@Lisias

**Comment by EExperiment** [comment]
I think you want this 
[KSP.log](https://github.com/net-lisias-ksp/KSPe/files/14463780/KSP.log)

@Lisias

**Comment by Lisias** [comment]
@EExperiment , by the looks of your `KSP.log`, the message is right.

You removed the `000_KSPe` directory, but left `001_KSPe.dll` on your game data. Worst, you left my fork of `Module Manager` on it too, and `KSPe` is a hard dependency for it.

So for all instances, the Message is correct.

What doesn't means that things can't be improved. Are you using CurseForge?

**Comment by EExperiment** [comment]
@Lisias I just wanted to try CurseForge, that's all. (I regret trying it.)

**Comment by Lisias** [comment]
@EExperiment ,

>  I just wanted to try CurseForge, that's all. 

Then you are right.

You found a bug on the Modular Management, it needs a mechanism to detect the thing was uninstalled and do a proper house cleaning.



> (I regret trying it.)

Sorry to hear about your frustration on CurseForge. I'm pretty sure I'm not helping on the issue right now.

Thanks for your time and patience. I can't change what happened, but now I can at least do something to prevent it from happening again.

Cheers!

(I will keep this open until I fix the problem)

**Comment by Lisias** [comment]
This will be tackled down on https://github.com/net-lisias-ksp/KSPe/issues/65
